module.exports = {
  hostsConfig: {
    localhost: "http://localhost:3000",
    production: "https://hub.testingtalks.com.au",
    staging: "https://hub.testingtalks.com.au",
  },
  pagesConfig: {
    home: {
      route: "/",
      regex: "^/$",
    },
    "create contact": {
      route: "/tasks/create",
      regex: "^/tasks/create$",
    },
    playground: {
      route: "/playground",
      regex: "^/playground",
    },
  },
  pageElementMappings: {
    common: {
      "header logo": "[data-id='header-logo']",
      search: "[data-id='search']",
      contact: "[data-id='contact']",
      "full name label": "[data-id='full-name-label']",
      name: "[data-id='name']",
      gender: "[data-id='gender']",
      phone: "[data-id='phone']",
      street: "[data-id='street']",
      city: "[data-id='city']",
      save: "[data-id='save-button']",
      playground: "[data-id='playground-button']",
    },
    "create contact": {
      "create contact header": "h1.create-contact",
    },
    home: {
      "contacts header": "[data-id='contacts']",
      create: "[data-id='add-button']",
      name: "[data-id='name']",
      "gender label": "[data-id='gender-label']",
      gender: "[data-id='gender']",
      "address label": "[data-id='address-label']",
      address: "[data-id='address']",
      edit: "[data-id='edit-button']",
      delete: "[data-id='delete-button']",
    },
    playground: {
      "female label": "[data-id='female-radio-button']",
      female: "[data-id='female-radio-button']",
      "male label": "[data-id='male-radio-button']",
      male: "[data-id='male-radio-button']",
      movies: "#movies-input",
      godfather: "li:text-is('The Godfather')",
      "dark knight": "li:text-is('The Dark Knight')",
      required: "#outlined-required",
      disabled: "#outlined-disabled",
      "validated label": "#outlined-error-helper-text-label",
      validated: "#outlined-error-helper-text",
      "error message": "#outlined-error-helper-text-helper-text",
      blue: "[data-id='blue-radio-button']",
      purple: "[data-id='purple-radio-button']",
      green: "[data-id='green-radio-button']",
      grey: "[data-id='grey-radio-button']",
      red: "[data-id='red-radio-button']",
      "basic iframe": "#basic-iframe",
      "new tab": "[data-id='new-tab-button']",
      "open window": "[data-id='open-window-button']",
      primary: "[data-id='primary-button']",
      secondary: "[data-id='secondary-button']",
      third: "[data-id='third-button']",
      "my-button": "[data-id='my-button']",
      "basic table": "[data-id='basic-table']",
      "switch one": "[data-id='switch-one']",
      "switch two": "[data-id='switch-two']",
      alert: "[data-id='browser-alert']",
      "error alert": "[data-id='error-alert']",
      "warning alert": "[data-id='warning-alert']",
      "info alert": "[data-id='info-alert']",
      "success alert": "[data-id='success-alert']",
      tooltip: "[data-id='tooltip']",
      textarea: "[data-id='textarea']",
      "show hide button": "[data-id='show-hide-button']",
      "show hide text": "[data-id='show-hide-text']",
      "first value": "[data-id='first-value']",
      "second value": "[data-id='second-value']",
      "third value": "[data-id='third-value']",
      "fourth value": "[data-id='fourth-value']",
      "fifth value": "[data-id='fifth-value']",
      "card header": "[data-id='card-header']",
      "card main": "[data-id='card-main']",
      "card type": "[data-id='card-type']",
      "card overview": "[data-id='card-overview']",
      "card action": "[data-id='card-action']",
      avatar: "[data-id='avatar']",
      "small avatar": "[data-id='small-avatar']",
      "dropdown button": "[data-id='drop-down-button']",
      profile: "[data-id='drop-down-profile']",
      "my-account": "[data-id='drop-down-my-account']",
      logout: "[data-id='drop-down-logout']",
      "select box": "#uncontrolled-native",
      "login email": "[data-id='email']",
      "login password": "[data-id='password']",
      "login button": "[data-id='login-button']",
      "email error": "[data-id='email-error']",
    },
  },
};
