name: Cucumber Playwright Test Framework
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    environment: dev
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies for react
        run: npm ci --force
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install dependencies for e2e
        run: cd ./e2e && npm ci
      - name: Run Cucumber tests
        run: cd e2e && ./run_tests.sh dev "@regression and not @production"
        env:
          PARALLEL: ${{ vars.PARALLEL }}
          RETRY: ${{ vars.RETRY }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          UI_AUTOMATION_HOST: ${{ vars.UI_AUTOMATION_HOST }}
          UI_AUTOMATION_BROWSER: ${{ vars.UI_AUTOMATION_BROWSER }}
          EMULATION: ${{ vars.EMULATION }}
          BROWSER_WIDTH: ${{ vars.BROWSER_WIDTH }}
          BROWSER_HEIGHT: ${{ vars.BROWSER_HEIGHT }}
          HEADLESS: ${{ vars.HEADLESS }}
          SCRIPT_TIMEOUT: ${{ vars.SCRIPT_TIMEOUT }}
          SELECTOR_TIMEOUT: ${{ vars.SELECTOR_TIMEOUT }}
          TEST_RESULTS_PATH: ${{ vars.TEST_RESULTS_PATH }}
          AXE_REPORT_PATH: ${{ vars.AXE_REPORT_PATH }}
          SCREENSHOTS_PATH: ${{ vars.SCREENSHOTS_PATH }}
          VIDEOS_PATH: ${{ vars.VIDEOS_PATH }}
          TRACES_PATH: ${{ vars.TRACES_PATH }}
          REPORT_PATH: ${{ vars.REPORT_PATH }}
          REPORT_NAME: ${{ vars.REPORT_NAME }}
          REPORT_TITLE: ${{ vars.REPORT_TITLE }}
          JSON_REPORT_PATH: ${{ vars.JSON_REPORT_PATH }}
          JSON_REPORT_FILE: ${{ vars.JSON_REPORT_FILE }}
          HTML_REPORT_FILE: ${{ vars.HTML_REPORT_FILE }}
          PWDEBUG: ${{ vars.PWDEBUG }}
          DEVTOOLS: ${{ vars.DEVTOOLS }}
          VAR_LOOKUP_TRIGGER: ${{ vars.VAR_LOOKUP_TRIGGER }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Report
          path: ./e2e/${{ vars.TEST_RESULTS_PATH }}/**
          retention-days: 2
